/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaatm;

import java.awt.CardLayout;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author LEGION
 */
public class GetCardNumber extends javax.swing.JFrame {

    public long cardNumber;
    dbInfoLoader dbinfo;
    private static long cardNum;
    private int count = 0;

    /**
     * Creates new form getCardNumber
     */
    public GetCardNumber() {
        initComponents();
        setIconImage();
    }

    private void switchToPanel(String panelName) {
        CardLayout cardLayout = (CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        CardPanel = new javax.swing.JPanel();
        inputPasswordLabel = new javax.swing.JLabel();
        cardNumberText = new javax.swing.JTextField();
        cardSubmit = new javax.swing.JButton();
        wrongCardLabel = new javax.swing.JLabel();
        PINPanel = new javax.swing.JPanel();
        pinPasswordField = new javax.swing.JLabel();
        pinNumberText = new javax.swing.JTextField();
        pinSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/logo/rastriyaBanijyaBank.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO RASTRIYE BANIJYA BANK ATM SERVICE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        MainPanel.setLayout(new java.awt.CardLayout());

        inputPasswordLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        inputPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inputPasswordLabel.setText("Please Input Your Card Number");

        cardNumberText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cardNumberText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cardSubmit.setBackground(new java.awt.Color(0, 0, 255));
        cardSubmit.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        cardSubmit.setForeground(new java.awt.Color(255, 255, 0));
        cardSubmit.setText("Submit");
        cardSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardSubmitActionPerformed(evt);
            }
        });

        wrongCardLabel.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        wrongCardLabel.setForeground(new java.awt.Color(255, 0, 0));
        wrongCardLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout CardPanelLayout = new javax.swing.GroupLayout(CardPanel);
        CardPanel.setLayout(CardPanelLayout);
        CardPanelLayout.setHorizontalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPanelLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(cardNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cardSubmit)
                .addGap(292, 292, 292))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wrongCardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CardPanelLayout.setVerticalGroup(
            CardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CardPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(inputPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cardNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(wrongCardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cardSubmit)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        MainPanel.add(CardPanel, "cardPanelCode");
        getRootPane().setDefaultButton(cardSubmit);

        pinPasswordField.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        pinPasswordField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pinPasswordField.setText("Please Input Your PIN Number");

        pinNumberText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pinNumberText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pinNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinNumberTextActionPerformed(evt);
            }
        });

        pinSubmit.setBackground(new java.awt.Color(0, 0, 255));
        pinSubmit.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        pinSubmit.setForeground(new java.awt.Color(255, 255, 0));
        pinSubmit.setText("Submit");
        pinSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PINPanelLayout = new javax.swing.GroupLayout(PINPanel);
        PINPanel.setLayout(PINPanelLayout);
        PINPanelLayout.setHorizontalGroup(
            PINPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PINPanelLayout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addComponent(pinSubmit)
                .addGap(291, 291, 291))
            .addGroup(PINPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PINPanelLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(PINPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PINPanelLayout.createSequentialGroup()
                            .addGap(249, 249, 249)
                            .addComponent(pinNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(226, 226, 226))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PINPanelLayout.createSequentialGroup()
                            .addComponent(pinPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(6, 6, 6)))))
        );
        PINPanelLayout.setVerticalGroup(
            PINPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PINPanelLayout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(pinSubmit)
                .addGap(52, 52, 52))
            .addGroup(PINPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PINPanelLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(pinPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(pinNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );

        MainPanel.add(PINPanel, "PINPanelCode");
        getRootPane().setDefaultButton(pinSubmit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardSubmitActionPerformed
        resetErrorLabel();

        String cardNumberInput = cardNumberText.getText();

        if (cardNumberInput.matches("\\d+")) {
            cardNumber = Long.parseLong(cardNumberInput);
            processCardNumber(cardNumber);
        } else {
            setErrorLabel("Wrong Card Number. Please Try Again with a valid one!");
        }
    }//GEN-LAST:event_cardSubmitActionPerformed

    private void resetErrorLabel() {
        wrongCardLabel.setText("");
    }

    private void setErrorLabel(String errorMessage) {
        wrongCardLabel.setText(errorMessage);
    }

    private void processCardNumber(long cardNumber) {
        dbinfo = new dbInfoLoader(cardNumber);

        if (dbinfo.getDbFlag() == 1) {
            setErrorLabel("Wrong Card Number. Please Try Again with a valid one!");
        } else if (!dbinfo.getdbStatus()) {
            setErrorLabel("This card has been blocked! Please contact the nearest Bank to resolve this issue! Thank You");
        } else {
            resetErrorLabel();
            cardNum = cardNumber;
            switchToPanel("PINPanelCode");
        }
    }


    private void pinSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinSubmitActionPerformed
        // TODO add your handling code here:
        String pinInput = pinNumberText.getText();
        //System.out.println(pinInput);
        if (pinInput.matches("\\d+")) {
            int pinNumber = Integer.parseInt(pinInput);
            System.out.println(dbinfo.getdbStatus());
            if (dbinfo.getdbStatus()) {
                if (count < 3) {
                    if (pinNumber == dbinfo.getDbPIN()) {
                        UserInterface ui = new UserInterface();
                        ui.setVisible(true);
                        this.dispose();
                    } else {
                        count++;
                        JOptionPane.showMessageDialog(null, "<html>Invalid PIN.<br> Please input the Valid PIN.<html>");
                    }
                } else {
                    dbinfo.setdbStatus();
                    JOptionPane.showMessageDialog(null, "Your card has been blocked. Please contact the nearest branch to fix this issue.");
                    switchToPanel("cardPanelCode");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Your card has been blocked. Please contact the nearest branch to fix this issue.");
            //wrongCardLabel.setText("Wrong Card Number. Please Try Again with valid one!");
        }
        System.out.println(count);
    }//GEN-LAST:event_pinSubmitActionPerformed

    private void pinNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinNumberTextActionPerformed

    //cant solve this
    public static long getCardNum() {
        return cardNum;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PINPanel;
    private javax.swing.JTextField cardNumberText;
    private javax.swing.JButton cardSubmit;
    private javax.swing.JLabel inputPasswordLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pinNumberText;
    private javax.swing.JLabel pinPasswordField;
    private javax.swing.JButton pinSubmit;
    private javax.swing.JLabel wrongCardLabel;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appIcon.png")));
    }
}
