/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaatm;

import java.awt.CardLayout;
import java.awt.Toolkit;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author LEGION
 */
public class UserInterface extends javax.swing.JFrame {

    dbInfoLoader dbLoad;

    /**
     * Creates new form getCardNumber
     */
    public UserInterface() {
        
        long cardNumber = GetCardNumber.getCardNum();
        dbLoad = new dbInfoLoader(cardNumber);
        
        initComponents();
        setIconImage();
    }
    
    private void switchToPanel(String panelName) {
        CardLayout cardLayout = (CardLayout) ChangeablePanel.getLayout();
        cardLayout.show(ChangeablePanel, panelName);
    }
    
    private void switchToTransferPanel(String transferPanelCode) {
        CardLayout cardLayout = (CardLayout) transferPanel.getLayout();
        cardLayout.show(transferPanel, transferPanelCode);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fastCashButtonGroup = new javax.swing.ButtonGroup();
        titlePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ChangeablePanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jDeposit = new javax.swing.JButton();
        jTransfer = new javax.swing.JButton();
        jPinChange = new javax.swing.JButton();
        jOther = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMiniStatement = new javax.swing.JButton();
        jBalanceEnquiry = new javax.swing.JButton();
        jCashWithdraw = new javax.swing.JButton();
        jFastCash = new javax.swing.JButton();
        transferPanel = new javax.swing.JPanel();
        receiverNumberPanel = new javax.swing.JPanel();
        selectedMenuTitle = new javax.swing.JLabel();
        AccLebel = new javax.swing.JLabel();
        AmtLebel = new javax.swing.JLabel();
        receiverAccountNumberTextField = new javax.swing.JTextField();
        transferAmountTextField = new javax.swing.JTextField();
        selectedMenuTitle1 = new javax.swing.JLabel();
        transferFirstSubmitButton = new javax.swing.JButton();
        transferPINPanel = new javax.swing.JPanel();
        selectedMenuTitle2 = new javax.swing.JLabel();
        AccLebel1 = new javax.swing.JLabel();
        PINPasswordField = new javax.swing.JTextField();
        selectedMenuTitle3 = new javax.swing.JLabel();
        transferSecondSubmitButton = new javax.swing.JButton();
        pinChangePanel = new javax.swing.JPanel();
        selectedMenuTitle4 = new javax.swing.JLabel();
        currentPINLabel = new javax.swing.JLabel();
        selectedMenuTitle5 = new javax.swing.JLabel();
        submitBtnPINChange = new javax.swing.JButton();
        currentPINField = new javax.swing.JPasswordField();
        nwePINLabel = new javax.swing.JLabel();
        newPINField = new javax.swing.JPasswordField();
        confirmPINLabel = new javax.swing.JLabel();
        confirmPINField = new javax.swing.JPasswordField();
        fastCashPanel = new javax.swing.JPanel();
        selectedMenuTitle6 = new javax.swing.JLabel();
        selectedMenuTitle7 = new javax.swing.JLabel();
        submitBtnFastCash = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        cashWithdrawPanel = new javax.swing.JPanel();
        selectedMenuTitle8 = new javax.swing.JLabel();
        withdrawAmountLabel = new javax.swing.JLabel();
        withdrawAmount = new javax.swing.JTextField();
        selectedMenuTitle9 = new javax.swing.JLabel();
        sBtnRecNum1 = new javax.swing.JButton();
        wrongWithDrawChoice = new javax.swing.JLabel();
        balanceInquiryPanel = new javax.swing.JPanel();
        selectedMenuTitle10 = new javax.swing.JLabel();
        userNameDisplayTab = new javax.swing.JLabel();
        backToMainMenuFromBalanceInquiry = new javax.swing.JButton();
        balanceDisplayTab = new javax.swing.JLabel();
        miniStatementPanel = new javax.swing.JPanel();
        selectedMenuTitle12 = new javax.swing.JLabel();
        sBtnRecNum3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        otherPanel = new javax.swing.JPanel();
        selectedMenuTitle13 = new javax.swing.JLabel();
        backToMainMenuFromOther = new javax.swing.JButton();
        depositPanel = new javax.swing.JPanel();
        selectedMenuTitle14 = new javax.swing.JLabel();
        amountToDepositLabel = new javax.swing.JLabel();
        amountToDeposit = new javax.swing.JTextField();
        selectedMenuTitle15 = new javax.swing.JLabel();
        submitBtnDeposit = new javax.swing.JButton();
        wrongDepositChoice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/logo/rastriyaBanijyaBank.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO RASTRIYE BANIJYA BANK ATM SERVICE");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        ChangeablePanel.setLayout(new java.awt.CardLayout());

        jDeposit.setBackground(new java.awt.Color(0, 0, 204));
        jDeposit.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jDeposit.setForeground(new java.awt.Color(255, 255, 0));
        jDeposit.setText("DEPOSIT");
        jDeposit.setToolTipText("");
        jDeposit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jDeposit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepositActionPerformed(evt);
            }
        });

        jTransfer.setBackground(new java.awt.Color(0, 0, 204));
        jTransfer.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jTransfer.setForeground(new java.awt.Color(255, 255, 0));
        jTransfer.setText("TRANSFER");
        jTransfer.setToolTipText("");
        jTransfer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTransfer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTransferActionPerformed(evt);
            }
        });

        jPinChange.setBackground(new java.awt.Color(0, 0, 204));
        jPinChange.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jPinChange.setForeground(new java.awt.Color(255, 255, 0));
        jPinChange.setText("PIN CHANGE");
        jPinChange.setToolTipText("");
        jPinChange.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPinChange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPinChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPinChangeActionPerformed(evt);
            }
        });

        jOther.setBackground(new java.awt.Color(0, 0, 204));
        jOther.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jOther.setForeground(new java.awt.Color(255, 255, 0));
        jOther.setText("OTHER");
        jOther.setToolTipText("");
        jOther.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jOther.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOtherActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><center>SELECT<br>TRANSACTION</html>");

        jMiniStatement.setBackground(new java.awt.Color(0, 0, 204));
        jMiniStatement.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jMiniStatement.setForeground(new java.awt.Color(255, 255, 0));
        jMiniStatement.setText("MINI STATEMENT");
        jMiniStatement.setToolTipText("");
        jMiniStatement.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMiniStatement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMiniStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiniStatementActionPerformed(evt);
            }
        });

        jBalanceEnquiry.setBackground(new java.awt.Color(0, 0, 204));
        jBalanceEnquiry.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jBalanceEnquiry.setForeground(new java.awt.Color(255, 255, 0));
        jBalanceEnquiry.setText("BALANCE ENQUIRY");
        jBalanceEnquiry.setToolTipText("");
        jBalanceEnquiry.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBalanceEnquiry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBalanceEnquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalanceEnquiryActionPerformed(evt);
            }
        });

        jCashWithdraw.setBackground(new java.awt.Color(0, 0, 204));
        jCashWithdraw.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jCashWithdraw.setForeground(new java.awt.Color(255, 255, 0));
        jCashWithdraw.setText("CASH WITHDRAW");
        jCashWithdraw.setToolTipText("");
        jCashWithdraw.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCashWithdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCashWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCashWithdrawActionPerformed(evt);
            }
        });

        jFastCash.setBackground(new java.awt.Color(0, 0, 204));
        jFastCash.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        jFastCash.setForeground(new java.awt.Color(255, 255, 0));
        jFastCash.setText("FAST CASH");
        jFastCash.setToolTipText("");
        jFastCash.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFastCash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jFastCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFastCashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jOther, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPinChange, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(jTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBalanceEnquiry, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(jMiniStatement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCashWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFastCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFastCash, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCashWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPinChange, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBalanceEnquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMiniStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOther, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jDeposit.getAccessibleContext().setAccessibleName("depositPanelCode");

        ChangeablePanel.add(menuPanel, "menuPanelCode");

        transferPanel.setLayout(new java.awt.CardLayout());

        selectedMenuTitle.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle.setText("Transfer Menu Selected");

        AccLebel.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        AccLebel.setText("Receiver's Account Number:");

        AmtLebel.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        AmtLebel.setText("Amount:");

        receiverAccountNumberTextField.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        receiverAccountNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiverAccountNumberTextFieldActionPerformed(evt);
            }
        });

        transferAmountTextField.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        transferAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferAmountTextFieldActionPerformed(evt);
            }
        });

        selectedMenuTitle1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle1.setText("Double Check the receivers account number before clicking submit");

        transferFirstSubmitButton.setBackground(new java.awt.Color(0, 0, 255));
        transferFirstSubmitButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        transferFirstSubmitButton.setForeground(new java.awt.Color(255, 255, 0));
        transferFirstSubmitButton.setText("Submit");
        transferFirstSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferFirstSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout receiverNumberPanelLayout = new javax.swing.GroupLayout(receiverNumberPanel);
        receiverNumberPanel.setLayout(receiverNumberPanelLayout);
        receiverNumberPanelLayout.setHorizontalGroup(
            receiverNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiverNumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(receiverNumberPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(receiverNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AmtLebel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AccLebel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(receiverNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiverAccountNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
            .addComponent(selectedMenuTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, receiverNumberPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transferFirstSubmitButton)
                .addGap(296, 296, 296))
        );
        receiverNumberPanelLayout.setVerticalGroup(
            receiverNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiverNumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(receiverNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccLebel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receiverAccountNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(receiverNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AmtLebel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(transferAmountTextField))
                .addGap(27, 27, 27)
                .addComponent(selectedMenuTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(transferFirstSubmitButton)
                .addGap(33, 33, 33))
        );

        transferPanel.add(receiverNumberPanel, "receiverNumberPanelcode");

        selectedMenuTitle2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle2.setText("Double Check the receivers account number before clicking submit");

        AccLebel1.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        AccLebel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AccLebel1.setText("PIN");

        PINPasswordField.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        PINPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PINPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PINPasswordFieldActionPerformed(evt);
            }
        });

        selectedMenuTitle3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle3.setText("Transaction performed cant be undone");

        transferSecondSubmitButton.setBackground(new java.awt.Color(0, 0, 255));
        transferSecondSubmitButton.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        transferSecondSubmitButton.setForeground(new java.awt.Color(255, 255, 0));
        transferSecondSubmitButton.setText("Submit");
        transferSecondSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferSecondSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transferPINPanelLayout = new javax.swing.GroupLayout(transferPINPanel);
        transferPINPanel.setLayout(transferPINPanelLayout);
        transferPINPanelLayout.setHorizontalGroup(
            transferPINPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPINPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(AccLebel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(PINPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transferPINPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transferPINPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transferSecondSubmitButton)
                .addGap(300, 300, 300))
            .addGroup(transferPINPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(transferPINPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(selectedMenuTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        transferPINPanelLayout.setVerticalGroup(
            transferPINPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPINPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(transferPINPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccLebel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PINPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addComponent(selectedMenuTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transferSecondSubmitButton)
                .addGap(64, 64, 64))
            .addGroup(transferPINPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(transferPINPanelLayout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(selectedMenuTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(169, Short.MAX_VALUE)))
        );

        transferPanel.add(transferPINPanel, "transferPINPanelCode");

        ChangeablePanel.add(transferPanel, "transferPanelCode");

        selectedMenuTitle4.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle4.setText("PIN Change Menu Selected");

        currentPINLabel.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        currentPINLabel.setText("Current PIN");

        selectedMenuTitle5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle5.setText("Remember your new pin. It can only be changed by bank if you forget!!");

        submitBtnPINChange.setBackground(new java.awt.Color(0, 0, 255));
        submitBtnPINChange.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        submitBtnPINChange.setForeground(new java.awt.Color(255, 255, 0));
        submitBtnPINChange.setText("Submit");
        submitBtnPINChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnPINChangeActionPerformed(evt);
            }
        });

        nwePINLabel.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        nwePINLabel.setText("New PIN");

        newPINField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPINFieldActionPerformed(evt);
            }
        });

        confirmPINLabel.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        confirmPINLabel.setText("Confirm PIN");

        javax.swing.GroupLayout pinChangePanelLayout = new javax.swing.GroupLayout(pinChangePanel);
        pinChangePanel.setLayout(pinChangePanelLayout);
        pinChangePanelLayout.setHorizontalGroup(
            pinChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinChangePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(selectedMenuTitle5, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinChangePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitBtnPINChange)
                .addGap(296, 296, 296))
            .addGroup(pinChangePanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(pinChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pinChangePanelLayout.createSequentialGroup()
                        .addComponent(currentPINLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentPINField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pinChangePanelLayout.createSequentialGroup()
                        .addComponent(nwePINLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newPINField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pinChangePanelLayout.createSequentialGroup()
                        .addComponent(confirmPINLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmPINField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        pinChangePanelLayout.setVerticalGroup(
            pinChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinChangePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pinChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currentPINLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(currentPINField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nwePINLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPINField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pinChangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPINField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPINLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(selectedMenuTitle5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(submitBtnPINChange)
                .addGap(33, 33, 33))
        );

        ChangeablePanel.add(pinChangePanel, "PINChangePanelCode");

        selectedMenuTitle6.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle6.setText("Fast Cash Menu Selected");

        selectedMenuTitle7.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle7.setText("Select the preferred Amount");

        submitBtnFastCash.setBackground(new java.awt.Color(0, 0, 255));
        submitBtnFastCash.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        submitBtnFastCash.setForeground(new java.awt.Color(255, 255, 0));
        submitBtnFastCash.setText("Submit");
        submitBtnFastCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnFastCashActionPerformed(evt);
            }
        });

        fastCashButtonGroup.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jRadioButton1.setText("500");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        fastCashButtonGroup.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jRadioButton2.setText("1000");

        fastCashButtonGroup.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jRadioButton3.setText("2000");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        fastCashButtonGroup.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jRadioButton4.setText("3000");

        fastCashButtonGroup.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jRadioButton5.setText("4000");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        fastCashButtonGroup.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jRadioButton6.setText("5000");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        fastCashButtonGroup.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jRadioButton7.setText("10000");

        fastCashButtonGroup.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jRadioButton8.setText("20000");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        fastCashButtonGroup.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jRadioButton9.setText("15000");

        javax.swing.GroupLayout fastCashPanelLayout = new javax.swing.GroupLayout(fastCashPanel);
        fastCashPanel.setLayout(fastCashPanelLayout);
        fastCashPanelLayout.setHorizontalGroup(
            fastCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fastCashPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fastCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedMenuTitle6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fastCashPanelLayout.createSequentialGroup()
                        .addComponent(selectedMenuTitle7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fastCashPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(fastCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(fastCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fastCashPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitBtnFastCash)
                        .addGap(240, 240, 240))
                    .addGroup(fastCashPanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(fastCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(fastCashPanelLayout.createSequentialGroup()
                                .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                                .addComponent(jRadioButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fastCashPanelLayout.createSequentialGroup()
                                .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                                .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fastCashPanelLayout.createSequentialGroup()
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)))
                .addGap(56, 56, 56))
        );
        fastCashPanelLayout.setVerticalGroup(
            fastCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fastCashPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectedMenuTitle7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fastCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addGap(18, 18, 18)
                .addGroup(fastCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(18, 18, 18)
                .addGroup(fastCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(submitBtnFastCash)
                .addGap(33, 33, 33))
        );

        ChangeablePanel.add(fastCashPanel, "fastCashPanelCode");

        selectedMenuTitle8.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle8.setText("Withdrawl Menu Selected");

        withdrawAmountLabel.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        withdrawAmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        withdrawAmountLabel.setText("Amount to Withdraw:");

        withdrawAmount.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        withdrawAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        withdrawAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawAmountActionPerformed(evt);
            }
        });

        selectedMenuTitle9.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle9.setText("Double Check the Withdrawl amount before clicking Proceeding");

        sBtnRecNum1.setBackground(new java.awt.Color(0, 0, 255));
        sBtnRecNum1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        sBtnRecNum1.setForeground(new java.awt.Color(255, 255, 0));
        sBtnRecNum1.setText("Submit");
        sBtnRecNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBtnRecNum1ActionPerformed(evt);
            }
        });

        wrongWithDrawChoice.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        wrongWithDrawChoice.setForeground(new java.awt.Color(255, 0, 0));
        wrongWithDrawChoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout cashWithdrawPanelLayout = new javax.swing.GroupLayout(cashWithdrawPanel);
        cashWithdrawPanel.setLayout(cashWithdrawPanelLayout);
        cashWithdrawPanelLayout.setHorizontalGroup(
            cashWithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cashWithdrawPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sBtnRecNum1)
                .addGap(296, 296, 296))
            .addGroup(cashWithdrawPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cashWithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectedMenuTitle8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cashWithdrawPanelLayout.createSequentialGroup()
                        .addComponent(withdrawAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(withdrawAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))))
            .addGroup(cashWithdrawPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(selectedMenuTitle9, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(cashWithdrawPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wrongWithDrawChoice, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                .addContainerGap())
        );
        cashWithdrawPanelLayout.setVerticalGroup(
            cashWithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashWithdrawPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(cashWithdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withdrawAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(wrongWithDrawChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(selectedMenuTitle9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(sBtnRecNum1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        ChangeablePanel.add(cashWithdrawPanel, "cashWithdrawlPanelCode");

        selectedMenuTitle10.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle10.setText("Balance inquiry Menu Selected");

        userNameDisplayTab.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        userNameDisplayTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        backToMainMenuFromBalanceInquiry.setBackground(new java.awt.Color(0, 0, 255));
        backToMainMenuFromBalanceInquiry.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        backToMainMenuFromBalanceInquiry.setForeground(new java.awt.Color(255, 255, 0));
        backToMainMenuFromBalanceInquiry.setText("Confirm");
        backToMainMenuFromBalanceInquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainMenuFromBalanceInquiryActionPerformed(evt);
            }
        });

        balanceDisplayTab.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        balanceDisplayTab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout balanceInquiryPanelLayout = new javax.swing.GroupLayout(balanceInquiryPanel);
        balanceInquiryPanel.setLayout(balanceInquiryPanelLayout);
        balanceInquiryPanelLayout.setHorizontalGroup(
            balanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, balanceInquiryPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToMainMenuFromBalanceInquiry)
                .addGap(296, 296, 296))
            .addGroup(balanceInquiryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(balanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedMenuTitle10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(balanceInquiryPanelLayout.createSequentialGroup()
                        .addGroup(balanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(balanceDisplayTab, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                            .addComponent(userNameDisplayTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        balanceInquiryPanelLayout.setVerticalGroup(
            balanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceInquiryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(userNameDisplayTab, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(balanceDisplayTab, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(backToMainMenuFromBalanceInquiry)
                .addGap(33, 33, 33))
        );

        ChangeablePanel.add(balanceInquiryPanel, "balanceInquiryPanelCode");

        selectedMenuTitle12.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle12.setText("Mini Statement Menu Selected");

        sBtnRecNum3.setBackground(new java.awt.Color(0, 0, 255));
        sBtnRecNum3.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        sBtnRecNum3.setForeground(new java.awt.Color(255, 255, 0));
        sBtnRecNum3.setText("Submit");
        sBtnRecNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBtnRecNum3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "S.N", "Transaction", "Date", "", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout miniStatementPanelLayout = new javax.swing.GroupLayout(miniStatementPanel);
        miniStatementPanel.setLayout(miniStatementPanelLayout);
        miniStatementPanelLayout.setHorizontalGroup(
            miniStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miniStatementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(miniStatementPanelLayout.createSequentialGroup()
                .addGroup(miniStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(miniStatementPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(miniStatementPanelLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(sBtnRecNum3)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        miniStatementPanelLayout.setVerticalGroup(
            miniStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miniStatementPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sBtnRecNum3)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        ChangeablePanel.add(miniStatementPanel, "miniStatementPanelCode");

        selectedMenuTitle13.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle13.setText("Other Menu Selected");

        backToMainMenuFromOther.setBackground(new java.awt.Color(0, 0, 255));
        backToMainMenuFromOther.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        backToMainMenuFromOther.setForeground(new java.awt.Color(255, 255, 0));
        backToMainMenuFromOther.setText("Main Menu");

        javax.swing.GroupLayout otherPanelLayout = new javax.swing.GroupLayout(otherPanel);
        otherPanel.setLayout(otherPanelLayout);
        otherPanelLayout.setHorizontalGroup(
            otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, otherPanelLayout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(backToMainMenuFromOther)
                .addGap(296, 296, 296))
            .addGroup(otherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        otherPanelLayout.setVerticalGroup(
            otherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164)
                .addComponent(backToMainMenuFromOther)
                .addGap(33, 33, 33))
        );

        ChangeablePanel.add(otherPanel, "otherPanelCode");

        selectedMenuTitle14.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle14.setText("Deposit  Menu Selected");

        amountToDepositLabel.setFont(new java.awt.Font("Poor Richard", 0, 18)); // NOI18N
        amountToDepositLabel.setText("Amount to Deposit:");

        amountToDeposit.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        amountToDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountToDepositActionPerformed(evt);
            }
        });

        selectedMenuTitle15.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        selectedMenuTitle15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectedMenuTitle15.setText("Double Check the receivers account number before clicking submit");

        submitBtnDeposit.setBackground(new java.awt.Color(0, 0, 255));
        submitBtnDeposit.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        submitBtnDeposit.setForeground(new java.awt.Color(255, 255, 0));
        submitBtnDeposit.setText("Submit");
        submitBtnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnDepositActionPerformed(evt);
            }
        });

        wrongDepositChoice.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        wrongDepositChoice.setForeground(new java.awt.Color(255, 0, 0));
        wrongDepositChoice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout depositPanelLayout = new javax.swing.GroupLayout(depositPanel);
        depositPanel.setLayout(depositPanelLayout);
        depositPanelLayout.setHorizontalGroup(
            depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitBtnDeposit)
                .addGap(296, 296, 296))
            .addComponent(selectedMenuTitle15, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
            .addGroup(depositPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(amountToDepositLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(amountToDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(depositPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wrongDepositChoice, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                .addContainerGap())
        );
        depositPanelLayout.setVerticalGroup(
            depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectedMenuTitle14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(selectedMenuTitle15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(depositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountToDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountToDepositLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(wrongDepositChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitBtnDeposit)
                .addGap(33, 33, 33))
        );

        ChangeablePanel.add(depositPanel, "depositPanelCode");
        depositPanel.getAccessibleContext().setAccessibleName("depositPanelCode");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ChangeablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChangeablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepositActionPerformed
        // TODO add your handling code here:
        
        switchToPanel("depositPanelCode");
        //double currentBalance = dbinfo.getUsrBalance();
        
        
    }//GEN-LAST:event_jDepositActionPerformed

    private void jTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTransferActionPerformed
        // TODO add your handling code here:
        switchToPanel("transferPanelCode");
        
//        CardLayout cardLayout = (CardLayout) transferPanel.getLayout();
//        cardLayout.show(transferPanel, "transferPanelCode");
    }//GEN-LAST:event_jTransferActionPerformed

    private void jPinChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPinChangeActionPerformed
        // TODO add your handling code here:
        switchToPanel("PINChangePanelCode");
    }//GEN-LAST:event_jPinChangeActionPerformed

    private void jOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOtherActionPerformed
        // TODO add your handling code here:
        switchToPanel("otherPanelCode");
    }//GEN-LAST:event_jOtherActionPerformed

    private void jMiniStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMiniStatementActionPerformed
        // TODO add your handling code here:
        switchToPanel("miniStatementPanelCode");
    }//GEN-LAST:event_jMiniStatementActionPerformed

    private void jBalanceEnquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalanceEnquiryActionPerformed
        userNameDisplayTab.setText("Dear " + dbLoad.getDbCardHolderName() + ",");
        balanceDisplayTab.setText(" Your Current Balance is Rs. " + dbLoad.getUsrBalance());
        switchToPanel("balanceInquiryPanelCode");
    }//GEN-LAST:event_jBalanceEnquiryActionPerformed

    private void jCashWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCashWithdrawActionPerformed
        // TODO add your handling code here:
        switchToPanel("cashWithdrawlPanelCode");
    }//GEN-LAST:event_jCashWithdrawActionPerformed

    private void jFastCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFastCashActionPerformed
        // TODO add your handling code here:
        switchToPanel("fastCashPanelCode");
    }//GEN-LAST:event_jFastCashActionPerformed

    private void receiverAccountNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiverAccountNumberTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_receiverAccountNumberTextFieldActionPerformed

    private void transferAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferAmountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferAmountTextFieldActionPerformed

    private void PINPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PINPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PINPasswordFieldActionPerformed

    private void newPINFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPINFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPINFieldActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void withdrawAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawAmountActionPerformed

    private void sBtnRecNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBtnRecNum3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sBtnRecNum3ActionPerformed

    private void amountToDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountToDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountToDepositActionPerformed

    private void backToMainMenuFromBalanceInquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainMenuFromBalanceInquiryActionPerformed
        // TODO add your handling code here:
        switchToPanel("menuPanelCode");
    }//GEN-LAST:event_backToMainMenuFromBalanceInquiryActionPerformed

    private void submitBtnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnDepositActionPerformed
        // TODO add your handling code here:
        String inputAmount = amountToDeposit.getText();
        if (inputAmount.matches("\\d+")) {
            int depositAmount = Integer.parseInt(inputAmount);
            if(dbLoad.depositBalance(depositAmount)) {
                JOptionPane.showMessageDialog(null, "Balance successfully deposited.");
            }
            
        }else {
            wrongDepositChoice.setText("Please input the amount in Digits only!");
            return;
        }
        amountToDeposit.setText("");
        switchToPanel("menuPanelCode");
    }//GEN-LAST:event_submitBtnDepositActionPerformed

    private void sBtnRecNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBtnRecNum1ActionPerformed
        // TODO add your handling code here:
        String inputAmount = withdrawAmount.getText();
        if (inputAmount.matches("\\d+")) {
            int withDrawAmount = Integer.parseInt(inputAmount);
            dbLoad.withDrawBalance(withDrawAmount);
            
        }else {
            wrongWithDrawChoice.setText("Please input the amount in Digits only!");
            return;
        }
        withdrawAmount.setText("");
        switchToPanel("menuPanelCode");
    }//GEN-LAST:event_sBtnRecNum1ActionPerformed

    private void submitBtnPINChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnPINChangeActionPerformed
        // TODO add your handling code here:
        char[] currentPINChars = currentPINField.getPassword();
        char[] newPINChars = newPINField.getPassword();
        char[] confirmPINChars = confirmPINField.getPassword();

        String currentStringPIN = String.valueOf(currentPINChars);
        String newStringPIN = String.valueOf(newPINChars);
        String confirmStringPIN = String.valueOf(confirmPINChars);

        if (currentStringPIN.matches("\\d+") && newStringPIN.matches("\\d+") && confirmStringPIN.matches("\\d+")) {
            int currentPIN = Integer.parseInt(currentStringPIN);
            int newPIN = Integer.parseInt(newStringPIN);
            int confirmPIN = Integer.parseInt(confirmStringPIN);
            int dbPIN = dbLoad.getDbPIN();
            
            if (dbPIN == currentPIN) {
                if ( newPIN == confirmPIN) {
                    dbLoad.setPIN(confirmPIN);
                    JOptionPane.showMessageDialog(null, "PIN successfully Changed.");
                    currentPINField.setText("");
                    newPINField.setText("");
                    confirmPINField.setText("");
                    switchToPanel("menuPanelCode");
                } else {
                     JOptionPane.showMessageDialog(null, "New PIN and Confirm PIN doesn't match!");
                     newPINField.setText("");
                     confirmPINField.setText("");
                }
            }else {
                JOptionPane.showMessageDialog(null, "Old PIN doesn't match.");
                currentPINField.setText("");
                newPINField.setText("");
                confirmPINField.setText("");
            }
        }else {
            wrongDepositChoice.setText("Please input the amount in Digits only!");
            //return;
        }
    }//GEN-LAST:event_submitBtnPINChangeActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void submitBtnFastCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnFastCashActionPerformed
        // TODO add your handling code here:
      ButtonModel selectedButtonModel = fastCashButtonGroup.getSelection();

      int selectedValue = 0;
        if (selectedButtonModel == jRadioButton1.getModel()) {
            selectedValue = 500;
        } else if (selectedButtonModel == jRadioButton2.getModel()) {
            selectedValue = 1000;
        } else if (selectedButtonModel == jRadioButton3.getModel()) {
            selectedValue = 2000;
        } else if (selectedButtonModel == jRadioButton4.getModel()) {
            selectedValue = 3000;
        } else if (selectedButtonModel == jRadioButton5.getModel()) {
            selectedValue = 4000;
        } else if (selectedButtonModel == jRadioButton6.getModel()) {
            selectedValue = 5000;
        } else if (selectedButtonModel == jRadioButton7.getModel()) {
            selectedValue = 10000;
        } else if (selectedButtonModel == jRadioButton8.getModel()) {
            selectedValue = 20000;
        } else if (selectedButtonModel == jRadioButton9.getModel()) {
            selectedValue = 15000;
        }
            if(dbLoad.withDrawBalance(selectedValue)) {
                JOptionPane.showMessageDialog(null, "Balance successfully Withdrawn.");
                JOptionPane.showMessageDialog(null, "Please Collect your Balance. ");
            }
            switchToPanel("menuPanelCode");
    }//GEN-LAST:event_submitBtnFastCashActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void transferSecondSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferSecondSubmitButtonActionPerformed
        // TODO add your handling code here:
        String receiverAccountNumber = receiverAccountNumberTextField.getText();
        String amount = transferAmountTextField.getText();
        String PIN = PINPasswordField.getText();

        long receiverAccountNum = Long.parseLong(receiverAccountNumber);
        double transferAmount = Double.parseDouble(amount);
        int pin = Integer.parseInt(PIN);

        if (pin == dbLoad.getDbPIN()) {
            if (dbLoad.depositBalanceforTransfer(transferAmount, receiverAccountNum) && dbLoad.withDrawBalance(transferAmount)) {
                JOptionPane.showMessageDialog(null, "Balance successfully Transferred to " + receiverAccountNum + " .");
            }
        } else {
            //custom title, error icon
            JOptionPane.showMessageDialog(null,
                    "Wrong PIN! Try using valid PIN.",
                    "wrong PIN",
                    JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showMessageDialog(null, "Cannot Transfer at the moment. Please try again later.");
        }

        switchToPanel("menuPanelCode");
    }//GEN-LAST:event_transferSecondSubmitButtonActionPerformed

    private void transferFirstSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferFirstSubmitButtonActionPerformed
        // TODO add your handling code here:
        switchToTransferPanel("transferPINPanelCode");
    }//GEN-LAST:event_transferFirstSubmitButtonActionPerformed

   
//    boolean arePinsEqual(String currentPIN, String newPIN, String confirmPIN) {
//        return currentPIN.equals(newPIN) && newPIN.equals(confirmPIN);
//    }

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccLebel;
    private javax.swing.JLabel AccLebel1;
    private javax.swing.JLabel AmtLebel;
    private javax.swing.JPanel ChangeablePanel;
    private javax.swing.JTextField PINPasswordField;
    private javax.swing.JTextField amountToDeposit;
    private javax.swing.JLabel amountToDepositLabel;
    private javax.swing.JButton backToMainMenuFromBalanceInquiry;
    private javax.swing.JButton backToMainMenuFromOther;
    private javax.swing.JLabel balanceDisplayTab;
    private javax.swing.JPanel balanceInquiryPanel;
    private javax.swing.JPanel cashWithdrawPanel;
    private javax.swing.JPasswordField confirmPINField;
    private javax.swing.JLabel confirmPINLabel;
    private javax.swing.JPasswordField currentPINField;
    private javax.swing.JLabel currentPINLabel;
    private javax.swing.JPanel depositPanel;
    private javax.swing.ButtonGroup fastCashButtonGroup;
    private javax.swing.JPanel fastCashPanel;
    private javax.swing.JButton jBalanceEnquiry;
    private javax.swing.JButton jCashWithdraw;
    private javax.swing.JButton jDeposit;
    private javax.swing.JButton jFastCash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jMiniStatement;
    private javax.swing.JButton jOther;
    private javax.swing.JButton jPinChange;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jTransfer;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel miniStatementPanel;
    private javax.swing.JPasswordField newPINField;
    private javax.swing.JLabel nwePINLabel;
    private javax.swing.JPanel otherPanel;
    private javax.swing.JPanel pinChangePanel;
    private javax.swing.JTextField receiverAccountNumberTextField;
    private javax.swing.JPanel receiverNumberPanel;
    private javax.swing.JButton sBtnRecNum1;
    private javax.swing.JButton sBtnRecNum3;
    private javax.swing.JLabel selectedMenuTitle;
    private javax.swing.JLabel selectedMenuTitle1;
    private javax.swing.JLabel selectedMenuTitle10;
    private javax.swing.JLabel selectedMenuTitle12;
    private javax.swing.JLabel selectedMenuTitle13;
    private javax.swing.JLabel selectedMenuTitle14;
    private javax.swing.JLabel selectedMenuTitle15;
    private javax.swing.JLabel selectedMenuTitle2;
    private javax.swing.JLabel selectedMenuTitle3;
    private javax.swing.JLabel selectedMenuTitle4;
    private javax.swing.JLabel selectedMenuTitle5;
    private javax.swing.JLabel selectedMenuTitle6;
    private javax.swing.JLabel selectedMenuTitle7;
    private javax.swing.JLabel selectedMenuTitle8;
    private javax.swing.JLabel selectedMenuTitle9;
    private javax.swing.JButton submitBtnDeposit;
    private javax.swing.JButton submitBtnFastCash;
    private javax.swing.JButton submitBtnPINChange;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JTextField transferAmountTextField;
    private javax.swing.JButton transferFirstSubmitButton;
    private javax.swing.JPanel transferPINPanel;
    private javax.swing.JPanel transferPanel;
    private javax.swing.JButton transferSecondSubmitButton;
    private javax.swing.JLabel userNameDisplayTab;
    private javax.swing.JTextField withdrawAmount;
    private javax.swing.JLabel withdrawAmountLabel;
    private javax.swing.JLabel wrongDepositChoice;
    private javax.swing.JLabel wrongWithDrawChoice;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appIcon.png")));
    }
}