/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserManagementSystem;

import java.awt.CardLayout;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Ellipse2D;
import java.awt.image.*;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author LEGION
 */
public class PasswordPanel extends javax.swing.JPanel {

    /**
     * Creates new form PasswordPanel
     */
    private JPanel mainPanel;
    public PasswordPanel(JPanel mainPanel) {
        initComponents();
        this.mainPanel = mainPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        switchToUserNamePanel = new javax.swing.JButton();
        circularLabel = new javax.swing.JLabel();

        jLabel1.setText("Password");

        switchToUserNamePanel.setText("switchToUserNamePanel");
        switchToUserNamePanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchToUserNamePanelActionPerformed(evt);
            }
        });

        circularLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        circularLabel.setMinimumSize(new java.awt.Dimension(100, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(switchToUserNamePanel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(circularLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(circularLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(switchToUserNamePanel)
                .addContainerGap(77, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void switchToUserNamePanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchToUserNamePanelActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "UserNamePanel");
        
         try {
             //ImageIcon icon = new ImageIcon("C:\\Users\\LEGION\\Documents\\NetBeansProjects\\JavaATM\\src\\atm\\logo\\rastriyaBanijyaBank.png");
        
            BufferedImage image = ImageIO.read(new File("C:\\Users\\LEGION\\Pictures\\frontFace.png"));
            System.out.println(circularLabel.getWidth());
            BufferedImage circularImage = getCircularImage(image, circularLabel.getWidth());
            ImageIcon circularIcon = new ImageIcon(circularImage);
            circularLabel.setIcon(circularIcon);
        } catch (IOException ex) {
    }
    }//GEN-LAST:event_switchToUserNamePanelActionPerformed

    

    
    private BufferedImage getCircularImage(BufferedImage image, int size) {
        BufferedImage circularImage = new BufferedImage(size, size, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = circularImage.createGraphics();
        //Graphics2D g2d = circularImage.createGraphics(image.getColorModel().getDefaultConfiguration());

        g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);

        double centerX = size / 2.0;
        double centerY = size / 2.0;
        double radius = size / 2.0;

        Ellipse2D.Double clip = new Ellipse2D.Double(centerX - radius, centerY - radius, size, size);
        g2d.clip(clip);

        g2d.drawImage(image, 0, 0, size, size, null);
        g2d.dispose();

        return circularImage;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel circularLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton switchToUserNamePanel;
    // End of variables declaration//GEN-END:variables
}
