/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserManagementSystem;

import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author LEGION
 */

public class UserName extends javax.swing.JPanel {

    /**
     * Creates new form UserName
     * @param mainPanel
     */
    private final JPanel mainPanel;
    public UserName(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        initComponents();
        scaleImage(); 
        
        System.out.println(label.getWidth());
    }
    
    public final void scaleImage() {
        
        ImageIcon icon = new ImageIcon("C:\\Users\\LEGION\\Documents\\NetBeansProjects\\JavaATM\\src\\atm\\logo\\rastriyaBanijyaBank.png");
        Image img = icon.getImage();
        //Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
        Image imgScale = img.getScaledInstance(40,40,Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        label.setIcon(scaledIcon);
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        switchToPasswordPanel = new javax.swing.JButton();
        label = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(0, 283));
        setVerifyInputWhenFocusTarget(false);

        switchToPasswordPanel.setText("switchToPasswordPanel");
        switchToPasswordPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchToPasswordPanelActionPerformed(evt);
            }
        });

        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(switchToPasswordPanel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(switchToPasswordPanel)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void switchToPasswordPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchToPasswordPanelActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "PasswordPanel");
    }//GEN-LAST:event_switchToPasswordPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel label;
    private javax.swing.JButton switchToPasswordPanel;
    // End of variables declaration//GEN-END:variables
}
